### ISSUE TITLE
Automatically delete measurement files

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooniprobe-android#96]
Especially relevant for unattended usage and possibly a requirement for orchestration, ooniprobe should automatically delete measurements that:

a. Are older than a certain configurable amount of time
b. Once a certain quota has been reached

Ideally we would store on the device the report ID and support fetching the individual measurements or full report from the ooniprobe backend for displaying it on the device.

**Comment by anadahz** [comment]
`ooniprobe`: 2.0.3
`measurement-kit`: 0.9.3

Measurement files are not automatically deleted.
Is this already implemented in `2.0.3` ?

**Comment by lorenzoPrimi** [comment]
@anadahz this has been closed because now we keep platform related issues only in the app repo.
Every ticket that affect both apps will be tracked in the ooni/probe repo:
This is the relevant one https://github.com/ooni/probe/issues/810
And maybe this one too https://github.com/ooni/probe/issues/811

For the deletion of the JSON we'll have to wait until the new explorer is out and there will be a way to fetch measurements.
